# Generated by Django 5.2.3 on 2025-06-24 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_groups_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("successful_deliveries", models.PositiveIntegerField(default=0)),
                ("unsuccessful_attempts", models.PositiveIntegerField(default=0)),
                ("total_messages_sent", models.PositiveIntegerField(default=0)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
