# Generated by Django 5.2.3 on 2025-06-15 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "date_and_time_first_launched",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время первой отправки"),
                ),
                (
                    "date_and_time_finish_launched",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата и время окончания отправки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Cоздана"), ("launched", "Запущена"), ("completed", "Завершена")],
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                ("clients", models.ManyToManyField(to="clients.client", verbose_name="Получатели")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mail.mail", verbose_name="Сообщение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
