# Generated by Django 5.2.3 on 2025-06-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="date_and_time_first_launched",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время первой отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("created", "Cоздана"), ("launched", "Запущена"), ("completed", "Завершена")],
                default="created",
                max_length=100,
                verbose_name="Статус",
            ),
        ),
    ]
