# Generated by Django 5.2.3 on 2025-06-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_date_and_time_first_launched_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttemptMailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datetime_attempt", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(choices=[("success", "Успешно"), ("failure", "Не успешно")], max_length=7),
                ),
                ("server_response", models.TextField()),
                ("mailing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailing.mailing")),
            ],
        ),
    ]
