# Generated by Django 5.2.3 on 2025-06-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_attemptmailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptmailing",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="mailing.mailing"
            ),
        ),
        migrations.AlterField(
            model_name="attemptmailing",
            name="server_response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
