# Generated by Django 5.2.3 on 2025-06-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject_letter", models.CharField(max_length=100, verbose_name="Тема письма")),
                ("body_letter", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Почтовое сообщение",
                "verbose_name_plural": "Почтовые сообщения",
            },
        ),
    ]
